name: update_date

# The workflow is triggered by changes to the repository, a scheduled monthly run, and manual dispatch.
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
         
      - name: Run Python Script
        run: python update_data.py 

      - name: Configure git
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and Push Changes
        run: |
          git add data/ # Voeg alleen bestanden in de map `data` toe
          git diff-index --quiet HEAD || git commit -m "Automated update by script"
          git push
